language: python
python: '3.6'
os: 'linux'
dist: bionic
cache: pip
install:
  - pip install -r ./requirements.txt -q
script:
  - BUILD_DIR=$(pwd)
  - cd torchfurnace/tests
  - python test_furnace.py
  - python test_img2lmdb.py
  - python test_tracer.py
  - echo 'log of test_tracer.py '
  - cat mine_network/logs/expn/log
branches:
  only:
#    - master
    - /^v.*$/
before_deploy:
  - cd $BUILD_DIR
  - echo 'deploy to pypi ...'
deploy:
  provider: pypi
  username: "__token__"
  password: $pypi_token
  skip_existing: true
  distributions: "sdist bdist_wheel"
  cleanup: true
  on:
    tags: true
after_deploy:
  - echo '!deploy successfully'